apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-pipeline-dev
resources:
  - namespace-config.yaml
  - redis.yaml
  - cache-api.yaml
images:
  - name: ghcr.io/jose-oran/gitops-pipeline-cache-api
    newTag: sha-eec728c7e5481e302af6e57eee04d7f4da6c3c08
